### ISSUE TITLE
Seems the descriptions are broken again

### ISSUE THREAD

**Issue by JanMP** [Swydo/meteor-graphql#12]
Running 0.2.0 descriptions aren't shown in grqphiql
#4

**Comment by jamiter** [comment]
Hi! Can you share the part of your schema where you add the descriptors? The tests are still passing so they should be there.

An example that is being tested: https://github.com/Swydo/meteor-graphql/blob/master/specs/examples/comments.graphql

I will have a closer look when I have the time.

**Comment by jamiter** [comment]
@JanMP, this is now fixed in 0.4.0.

It now uses string descriptors introduced in `graphql` 0.12. See https://github.com/graphql/graphql-js/pull/927

This means you will need to use the new syntax if you want descriptions:

```graphql
"""
This is a multi line description
Pretty cool, right?
"""
type Foo {
  "And this is a single line description"
  name: String
}

# And comments are now simply comments, always
```

Let me know if you run into any issues.

**Comment by macrozone** [comment]
hi @jamiter I updated to 0.4.0 but descriptions do not work. Anything i can try out?

Edit: it was actually a problem with the version of apollo-server-express or graphql-tools

**Comment by pozylon** [comment]
@macrozone I just updated to graphql 0.12. Some apollo-engine dependencies demand 0.11, did you solve that or do you just ignore the npm warnings?

`
npm WARN apollo-cache-control@0.0.7 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.1.1 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-graphql@1.5.0 requires a peer of graphql@^0.10.1 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.0.5 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
`
