### ISSUE TITLE
TypeDefs split up into multiple files

### ISSUE THREAD

**Issue by elie222** [Swydo/meteor-graphql#17]
We were doing something like this before:
```
import playerSchema from 'playerSchema';

`
${playerSchema}
${fixtureSchema}
${clubSchema}
`
```

Is this possible with this package? We no longer get a string when importing the `.graphql` files. So how would this be done?

**Comment by jamiter** [comment]
The cool thing is that you can use import comments, that will just work:

```graphql
#import "./playerSchema.graphql"
#import "./fixtureSchema.graphql"
#import "./clubSchema.graphql"

type AnotherType {
  foo: String
}
```

Edit: I've added an example in the README as well.

**Comment by jamiter** [comment]
Did this answer your question? Please let me know if something is still unclear.
