### ISSUE TITLE
Support Field Descriptions

### ISSUE THREAD

**Issue by joncursi** [Swydo/meteor-graphql#4]
I noticed that when I use this package, field descriptions stopped showing up in GraphiQL. Consider the example:

`test.graphql`:

```graphql
#import './channel.graphql'
#import './user.graphql'

# test type description
type Query {
  # test field description
  channels: [Channel],
  # test field description
  user: User,
}
```

GraphiQL shows "No Description" for all types and fields. Do I need to do some sort of configuraton to get the descriptions to show up? Thanks!

**Comment by jamiter** [comment]
Hi, thanks for reporting this. Under the hood this package is using the loader from [graphql-tag](https://github.com/apollographql/graphql-tag). They released new versions with some fixes so updating the version might fix this. If not, the bug should be reported in said package.

I'll update the version and see if it fixes the issue.

**Comment by jamiter** [comment]
No luck so far. It doesn't seem to do anything with the comments. I'll pass this on to the graphql-tag package.

**Comment by jamiter** [comment]
I created a PR for `graphql-tag`, so hopefully we'll get this in soon. If you would like to support the PR, please comment or add a 👍  in the following thread: https://github.com/apollographql/graphql-tag/pull/99

Cheers

**Comment by jamiter** [comment]
@joncursi and @smothers, good news! The PR got merged and I added it to this package as well. So field descriptors are now supported! Please update to version `0.1.0`.
